### ISSUE TITLE
Mock data

### ISSUE THREAD

**Issue by 88jonhan** [Razew/suvnet23-household-backsidegang#14]

**Comment by 88jonhan** [comment]
Need initial data to work with, 1-2 households with chores, a couple of users with different roles and assigned to the different households

**Comment by frankenwino** [comment]
Suggestion for DB schema & mocked data. Need to decide on the storage / auth solution though.

https://github.com/Razew/suvnet23-household-backsidegang/wiki/Local-Supabase-Dev-Instance#create-seed-files

**Comment by 88jonhan** [comment]
> Suggestion for DB schema & mocked data. Need to decide on the storage / auth solution though.
> 
> https://github.com/Razew/suvnet23-household-backsidegang/wiki/Local-Supabase-Dev-Instance#create-seed-files

I've added properties to the types and mocked some objects based on your mocked query.

added HouseholdUserProfile, atleast as a temporary solution
![image](https://github.com/user-attachments/assets/0af91f03-c34a-4848-8193-2e816319324b)7

don't know how we will set up chore_to_user yet.

need to decide if we want to have the foreign key as a property, or map to an actual object .

**Comment by 88jonhan** [comment]
added this: 
![image](https://github.com/user-attachments/assets/e35cacf0-b096-496d-9339-382bc1327b69)
