### ISSUE TITLE
Edit splashscreen

### ISSUE THREAD

**Issue by alexjoelaid** [Razew/suvnet23-household-backsidegang#20]
- [x] Add logo
- [ ] Style

<img width="165" alt="Screenshot 2024-10-11 at 11 10 56" src="https://github.com/user-attachments/assets/0733d852-4af6-4665-9712-0944f82578ae">

**Comment by Razew** [comment]
P.S. I happened to add the logo when I set up navigation, see `screens/LoadingScreen.tsx` in pull request: https://github.com/Razew/suvnet23-household-backsidegang/pull/35 
More styling is required though!
